### PR TITLE
Print all assembly functions if function path not set

### PR DESCRIPTION
**Pull request by HaronK**
I've made path command line argument optional so program prints all available assembly functions if it is not specified.

### CODE REVIEW

**Comment by HaronK** [comment]
Oops! Forgot to update tests...

**Comment by gnzlbg** [comment]
Thank you for this!

**Comment by gnzlbg** [comment]
Note that CI uses Rust 1.25.0. What version are you using locally to test this? If you are using 1.26.0 locally you might need to update the version on CI to 1.26.0 but then that requires updating the assembly generated for all the tests :/ Might be better to just test this with 1.25.0 locally and leave the tests unchanged.

**Comment by HaronK** [comment]
According to CI console it compiles with 1.28.0-nightly.

**Comment by gnzlbg** [comment]
That might be the case for `appveyor`, but its definetely not the case for travis.

**Comment by gnzlbg** [comment]
I think I forgot to pin appveyor to 1.25.0, if travis passes I'll merge this, I can update appveyor later :)

**Comment by HaronK** [comment]
Then I have to revert my last change to the tests...

**Comment by gnzlbg** [comment]
Sorry.. the assembly generated by each rustc version is a tiny bit different, and updating the test with every nightly was a pain. So I fixed it to a rustc version and it just happened to produce the same results as the nightly for a while, but it seems that this is no longer the case :/

**Comment by HaronK** [comment]
By mistake did double revert.

**Comment by gnzlbg** [comment]
Thanks! I just published a new version.

**Comment by HaronK** [comment]
Cool!

**Pull request merged**
