### PR TITLE
Do not use `--debug` flag when calling to `cargo`

### PR DESCRIPTION
**Pull request by hcpl**
Cargo doesn't have such a flag and defaults to debug builds when no `--release` is provided.

### CODE REVIEW

**Comment by gnzlbg** [comment]
Thanks! It looks like the `.gitignore` and `Cargo.lock` where added by mistake. Could you remove those? Otherwise LGTM :)

**Comment by hcpl** [comment]
I added them on purpose: when I did `cargo install cargo-asm` today, I noticed some dependencies that are compiled several times with different versions. They make the build longer and probably increase the size of the binary (this one may not be an issue thanks to LTO). So I thought `Cargo.lock` would be useful to pin down the set of dependencies that works with minimum duplications.

And `.gitignore` here is because I was surprised at the number 304 of untracked files after compiling `cargo-asm`. Turns out, those we files from `target/` and swap files from vim.

Though if you do have a reason to omit those files, I might step back. Just wanted to point out those issues along with the main goal of this PR :)

**Comment by gnzlbg** [comment]
Makes sense to me, thanks!

**Comment by gnzlbg** [comment]
@hcpl i've released 0.1.13 with the fix

**Comment by hcpl** [comment]
Many thanks!

**Pull request merged**
